server {
    listen 80;

    location /api/users/ {
        proxy_pass http://user-service:3001/;
    }

    location /api/products/ {
        proxy_pass http://product-service:3002/;
    }

    location /api/orders/ {
        proxy_pass http://order-service:3003/;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}
